<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->insert([
            [
                'id'=> '1',
                'name'=> '主页',
                'parent_id'=> '0',
                'icon'=> '',
                'url'=> 'home',
                'description'=> '主页',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
           ],[
                'id'=> '2',
                'name'=> '教务',
                'parent_id'=> '0',
                'icon'=> '',
                'url'=> 'teachtask',
                'description'=> '教务',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '3',
                'name'=> '运营',
                'parent_id'=> '0',
                'icon'=> '',
                'url'=> 'operative',
                'description'=> '运营',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '4',
                'name'=> '用户',
                'parent_id'=> '0',
                'icon'=> '',
                'url'=> 'user',
                'description'=> '用户',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '5',
                'name'=> '订单',
                'parent_id'=> '0',
                'icon'=> '',
                'url'=> 'order',
                'description'=> '订单',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '6',
                'name'=> '系统设置',
                'parent_id'=> '0',
                'icon'=> '',
                'url'=> 'rbacment',
                'description'=> '系统设置',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '7',
                'name'=> '后台主页',
                'parent_id'=> '1',
                'icon'=> 'el-icon-erp-icon-home',
                'url'=> 'home',
                'description'=> '后台主页',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '8',
                'name'=> '课程管理',
                'parent_id'=> '2',
                'icon'=> 'el-icon-erp-icon-ic_school',
                'url'=> 'teachtask',
                'description'=> '课程管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '9',
                'name'=> '视频库',
                'parent_id'=> '2',
                'icon'=> 'el-icon-erp-icon-youtube-play',
                'url'=> 'videos',
                'description'=> '视频库',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '10',
                'name'=> '栏目管理',
                'parent_id'=> '2',
                'icon'=> 'el-icon-erp-icon-dns',
                'url'=> 'colment',
                'description'=> '栏目管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '11',
                'name'=> '标签管理',
                'parent_id'=> '2',
                'icon'=> 'el-icon-erp-icon-widgets',
                'url'=> 'sortment',
                'description'=> '标签管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '12',
                'name'=> '评论管理',
                'parent_id'=> '2',
                'icon'=> 'el-icon-erp-icon-message-processing',
                'url'=> 'revment',
                'description'=> '评论管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '13',
                'name'=> '消息推送管理',
                'parent_id'=> '3',
                'icon'=> 'el-icon-erp-icon-ic_forum',
                'url'=> 'operative',
                'description'=> '消息推送管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '14',
                'name'=> '广告管理',
                'parent_id'=> '3',
                'icon'=> 'el-icon-erp-icon-image',
                'url'=> 'adalert',
                'description'=> '广告管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '15',
                'name'=> 'VIP会员管理',
                'parent_id'=> '3',
                'icon'=> 'el-icon-erp-icon-vimeo',
                'url'=> 'vipment',
                'description'=> 'VIP会员管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '16',
                'name'=> '讲师信息管理',
                'parent_id'=> '3',
                'icon'=> 'el-icon-erp-icon-account-plus',
                'url'=> 'instment',
                'description'=> '讲师信息管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '17',
                'name'=> '主页信息管理',
                'parent_id'=> '3',
                'icon'=> 'el-icon-erp-icon-ic_important_devices',
                'url'=> 'hoinfment',
                'description'=> '主页信息管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '18',
                'name'=> '公众号管理',
                'parent_id'=> '3',
                'icon'=> 'el-icon-erp-icon-0023',
                'url'=> 'pubnument',
                'description'=> '公众号管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'id'=> '19',
                'name'=> '用户管理',
                'parent_id'=> '4',
                'icon'=> 'el-icon-erp-icon-yonghu',
                'url'=> 'user',
                'description'=> '用户管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '20',
                'name'=> '订单管理',
                'parent_id'=> '5',
                'icon'=> 'el-icon-erp-icon-clipboard-text',
                'url'=> 'order',
                'description'=> '订单管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '21',
                'name'=> '权限管理',
                'parent_id'=> '6',
                'icon'=> 'el-icon-erp-icon-lock',
                'url'=> 'rbacment',
                'description'=> '权限管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '22',
                'name'=> '角色管理',
                'parent_id'=> '6',
                'icon'=> 'el-icon-erp-icon-ic_contacts',
                'url'=> 'rolement',
                'description'=> '角色管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'id'=> '23',
                'name'=> '账号管理',
                'parent_id'=> '6',
                'icon'=> 'el-icon-erp-icon-account-multiple',
                'url'=> 'accment',
                'description'=> '账号管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'id'=> '24',
                'name'=> '教务设置',
                'parent_id'=> '3',
                'icon'=> 'el-icon-erp-icon-message-video',
                'url'=> 'eduset',
                'description'=> '账号管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
           ], [
                'id'=> '25',
                'name'=> '系统操作日志',
                'parent_id'=> '6',
                'icon'=> 'el-icon-erp-icon-ic_touch_app',
                'url'=> 'syslog',
                'description'=> '系统操作日志',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '26',
                'name'=> '会销管理',
                'parent_id'=> '3',
                'icon'=> 'el-icon-erp-icon-calendar-text',
                'url'=> 'SaleMent',
                'description'=> '会销管理',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id'=> '27',
                'name'=> '通用设置',
                'parent_id'=> '6',
                'icon'=> 'el-icon-erp-icon-settings',
                'url'=> 'CurrencyMent',
                'description'=> '通用设置',
                'is_nav' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
